name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm i

      - name: build
        run: npm run build
      - name: prepare docs
        run: rm -rf docs && mv build docs
      - name: commit docs
        run: |
          git config --global user.name 'ravichandra-me'
          git config --global user.email 'ravichandra-me@users.noreply.github.com'
          git commit -am "Automated deploy build"
          git push
